branch-defaults:
  main:
    environment: Georgeboard-env
environment-defaults:
  Georgeboard-env:
    branch: null
    repository: null
global:
  application_name: georgeboard
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: geocolumbus
  repository: null
  sc: git
  workspace_type: Application
